@baseUrl = http://localhost:3000/api

### Create User
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "username": "aaabbbccc"
}



### List Users 
GET {{baseUrl}}/users  HTTP/1.1

### Create Exercise
POST {{baseUrl}}/users/64095af1dec376c0e6dc3f2b/exercises HTTP/1.1
Content-Type: application/json

{
    "description": "BDL",
    "duration": 60,
    "username": "aaabbbccc",
    "date": "2020-01-32"
}


### Get Users
GET {{baseUrl}}/users/64095af1dec376c0e6dc3f2b/exercises HTTP/1.1

### Get logs
GET {{baseUrl}}/users/64095af1dec376c0e6dc3f2b/logs?from=2023-01-32 HTTP/1.1